services:
  idempotencia-qa-back:
    build:
      context: .
      dockerfile: Dockerfile
    image: idempotencia-qa-back:latest
    env_file:
      - .env
    container_name: idempotencia-qa-back
    restart: unless-stopped
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    ports:
      - "5556:5556"
    networks:
      - red-proxy
    mem_limit: 384m
    cpus: 0.3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  red-proxy:
    external: true